name: Feature Request ✨
description: Suggest an idea for this project
title: "[Feature] "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below.

  - type: input
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important to you?

  - type: input
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
